/* ortMatlab.c
   Generated by gSOAP 2.8.14 from rdlite.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/
#include "ortMatlab.h"

mxArray* c_to_mx_soapSparseArray(struct soapSparseArray a)
{
  mxArray *b;
  b = mxCreateSparse(a.num_rows, a.num_columns, a.nzmax, mxREAL);
  mxSetIr(b,a.ir);
  mxSetJc(b,a.jc);
  mxSetPr(b,a.pr);
  return b;
}

mxArray* mx_to_c_soapSparseArray(const mxArray *a, struct soapSparseArray *b)
{
  if(!mxIsSparse(a))
    {
      mexErrMsgTxt("Input should be a sparse array.");
    }
  /* Get the starting positions of the data in the sparse array. */  
  b->pr = mxGetPr(a);
  b->ir = mxGetIr(a);
  b->jc = mxGetJc(a);
  b->num_columns = mxGetN(a);
  b->num_rows = mxGetM(a);
  b->nzmax = mxGetNzmax(a);
}

mxArray* c_to_mx_byte(char a)
{
	mxArray  *fout;
	char buf[2];
	buf[0] = a;
	buf[1] = '\0';
	fout = mxCreateString(buf);
	if (!fout)
		mexErrMsgTxt("Could not create mxArray.");
	return fout;
}

void mx_to_c_byte(const mxArray *a, char *b)
{
	int ret;
	char buf[2];
	ret = mxGetString(a, buf, 2);
	mexPrintf("ret = %d, buf = %s", ret, buf);
	*b = buf[0];

}

mxArray* c_to_mx_short(short a)
{
	mxArray  *fout;
	int ndim = 1, dims[1] = {1};
	fout = mxCreateNumericArray(ndim, dims, mxINT16_CLASS, mxREAL);
	short *temp = (short *)mxGetPr(fout);
	if (!fout)
		mexErrMsgTxt("Could not create mxArray.");
	if (!temp) 
		mexErrMsgTxt("matlab_array_c_to_mx: Pointer to data is NULL");
	*temp++= a;
	return fout;
}

void mx_to_c_short(const mxArray *a, short *b)
{
	double* data = (double*)mxGetData(a);
	*b = (short)*data;

}

mxArray* c_to_mx_int(int a)
{
	mxArray  *fout;
	int ndim = 1, dims[1] = {1};
	fout = mxCreateNumericArray(ndim, dims, mxINT32_CLASS, mxREAL);
	int *temp = (int *)mxGetPr(fout);
	if (!fout)
		mexErrMsgTxt("Could not create mxArray.");
	if (!temp) 
		mexErrMsgTxt("matlab_array_c_to_mx: Pointer to data is NULL");
	*temp++= a;
	return fout;
}

void mx_to_c_int(const mxArray *a, int *b)
{
	double* data = (double*)mxGetData(a);
	*b = (int)*data;

}

mxArray* c_to_mx_LONG64(LONG64 a)
{
	mxArray  *fout;
	int ndim = 1, dims[1] = {1};
	fout = mxCreateNumericArray(ndim, dims, mxINT64_CLASS, mxREAL);
	LONG64 *temp = (LONG64 *)mxGetPr(fout);
	if (!fout)
		mexErrMsgTxt("Could not create mxArray.");
	if (!temp) 
		mexErrMsgTxt("matlab_array_c_to_mx: Pointer to data is NULL");
	*temp++= a;
	return fout;
}

void mx_to_c_LONG64(const mxArray *a, LONG64 *b)
{
	double* data = (double*)mxGetData(a);
	*b = (LONG64)*data;

}

mxArray* c_to_mx_xsd__unsignedByte(unsigned char a)
{
	mxArray  *fout;
	char buf[2];
	buf[0] = a;
	buf[1] = '\0';
	fout = mxCreateString(buf);
	if (!fout)
		mexErrMsgTxt("Could not create mxArray.");
	return fout;
}

void mx_to_c_xsd__unsignedByte(const mxArray *a, unsigned char *b)
{
	int ret;
	char buf[2];
	ret = mxGetString(a, buf, 2);
	mexPrintf("ret = %d, buf = %s", ret, buf);
	*b = buf[0];

}

mxArray* c_to_mx_unsignedByte(unsigned char a)
{
	mxArray  *fout;
	char buf[2];
	buf[0] = a;
	buf[1] = '\0';
	fout = mxCreateString(buf);
	if (!fout)
		mexErrMsgTxt("Could not create mxArray.");
	return fout;
}

void mx_to_c_unsignedByte(const mxArray *a, unsigned char *b)
{
	int ret;
	char buf[2];
	ret = mxGetString(a, buf, 2);
	mexPrintf("ret = %d, buf = %s", ret, buf);
	*b = buf[0];

}

mxArray* c_to_mx_unsignedShort(unsigned short a)
{
	mxArray  *fout;
	int ndim = 1, dims[1] = {1};
	fout = mxCreateNumericArray(ndim, dims, mxUINT16_CLASS, mxREAL);
	unsigned short *temp = (unsigned short *)mxGetPr(fout);
	if (!fout)
		mexErrMsgTxt("Could not create mxArray.");
	if (!temp) 
		mexErrMsgTxt("matlab_array_c_to_mx: Pointer to data is NULL");
	*temp++= a;
	return fout;
}

void mx_to_c_unsignedShort(const mxArray *a, unsigned short *b)
{
	double* data = (double*)mxGetData(a);
	*b = (unsigned short)*data;

}

mxArray* c_to_mx_unsignedInt(unsigned int a)
{
	mxArray  *fout;
	int ndim = 1, dims[1] = {1};
	fout = mxCreateNumericArray(ndim, dims, mxUINT32_CLASS, mxREAL);
	unsigned int *temp = (unsigned int *)mxGetPr(fout);
	if (!fout)
		mexErrMsgTxt("Could not create mxArray.");
	if (!temp) 
		mexErrMsgTxt("matlab_array_c_to_mx: Pointer to data is NULL");
	*temp++= a;
	return fout;
}

void mx_to_c_unsignedInt(const mxArray *a, unsigned int *b)
{
	double* data = (double*)mxGetData(a);
	*b = (unsigned int)*data;

}

mxArray* c_to_mx_ns2__QueryResponse(struct ns2__QueryResponse a)
{
	const char* fnames[] = {"result"}; /* pointers to member field names */
	int rows = 1, cols = 1;
	int index = 0;
	int number_of_fields = 1;
	mxArray *struct_array_ptr;
	/* Create a 1x1 struct matrix for output  */
	struct_array_ptr = mxCreateStructMatrix(rows, cols, number_of_fields, fnames);
	mexPrintf("6");
	if(struct_array_ptr == NULL) {
		mexPrintf("COULDNT CREATE A MATRIX");}
	mexPrintf("7");
	{mxArray *fout = c_to_mx_PointerTons2__TagValueArray(a.result);
	mxSetField(struct_array_ptr, index,"result" , fout);}
	return struct_array_ptr;
}

void mx_to_c_ns2__QueryResponse(const mxArray* a, struct ns2__QueryResponse *b)
{
	if(!mxIsStruct(a))
		mexErrMsgTxt("Input must be a structure.");
	{mxArray *tmp = mxGetField(a,0,"result");
	if (!tmp) {
		mexErrMsgTxt("Above member field is empty!");
	}
	mx_to_c_PointerTons2__TagValueArray(tmp,&(b->result));}

}

mxArray* c_to_mx_ns2__ReadResponse(struct ns2__ReadResponse a)
{
	const char* fnames[] = {"result"}; /* pointers to member field names */
	int rows = 1, cols = 1;
	int index = 0;
	int number_of_fields = 1;
	mxArray *struct_array_ptr;
	/* Create a 1x1 struct matrix for output  */
	struct_array_ptr = mxCreateStructMatrix(rows, cols, number_of_fields, fnames);
	mexPrintf("6");
	if(struct_array_ptr == NULL) {
		mexPrintf("COULDNT CREATE A MATRIX");}
	mexPrintf("7");
	{mxArray *fout = c_to_mx_PointerTons2__TagValueArray(a.result);
	mxSetField(struct_array_ptr, index,"result" , fout);}
	return struct_array_ptr;
}

void mx_to_c_ns2__ReadResponse(const mxArray* a, struct ns2__ReadResponse *b)
{
	if(!mxIsStruct(a))
		mexErrMsgTxt("Input must be a structure.");
	{mxArray *tmp = mxGetField(a,0,"result");
	if (!tmp) {
		mexErrMsgTxt("Above member field is empty!");
	}
	mx_to_c_PointerTons2__TagValueArray(tmp,&(b->result));}

}

mxArray* c_to_mx_PointerTons2__Query(struct ns2__Query *a)
{
	mxArray  *fout;
	fout = c_to_mx_ns2__Query(*a);
	return fout;
}

void mx_to_c_PointerTons2__Query(const mxArray* a,struct ns2__Query **b)
{
	mx_to_c_ns2__Query(a,*b);

}

mxArray* c_to_mx_PointerTons2__QueryResponse(struct ns2__QueryResponse *a)
{
	mxArray  *fout;
	fout = c_to_mx_ns2__QueryResponse(*a);
	return fout;
}

void mx_to_c_PointerTons2__QueryResponse(const mxArray* a,struct ns2__QueryResponse **b)
{
	mx_to_c_ns2__QueryResponse(a,*b);

}

mxArray* c_to_mx_PointerTons2__Read(struct ns2__Read *a)
{
	mxArray  *fout;
	fout = c_to_mx_ns2__Read(*a);
	return fout;
}

void mx_to_c_PointerTons2__Read(const mxArray* a,struct ns2__Read **b)
{
	mx_to_c_ns2__Read(a,*b);

}

mxArray* c_to_mx_PointerTons2__ReadResponse(struct ns2__ReadResponse *a)
{
	mxArray  *fout;
	fout = c_to_mx_ns2__ReadResponse(*a);
	return fout;
}

void mx_to_c_PointerTons2__ReadResponse(const mxArray* a,struct ns2__ReadResponse **b)
{
	mx_to_c_ns2__ReadResponse(a,*b);

}

mxArray* c_to_mx_PointerTostd__string(std::string *a)
{
	mxArray  *fout;
	fout = c_to_mx_std__string(*a);
	return fout;
}

void mx_to_c_PointerTostd__string(const mxArray* a,std::string **b)
{
	mx_to_c_std__string(a,*b);

}

mxArray* c_to_mx_PointerTons2__TagIdArray(ns2__TagIdArray *a)
{
	mxArray  *fout;
	fout = c_to_mx_ns2__TagIdArray(*a);
	return fout;
}

void mx_to_c_PointerTons2__TagIdArray(const mxArray* a,ns2__TagIdArray **b)
{
	mx_to_c_ns2__TagIdArray(a,*b);

}

mxArray* c_to_mx_PointerTons2__TagValueArray(ns2__TagValueArray *a)
{
	mxArray  *fout;
	fout = c_to_mx_ns2__TagValueArray(*a);
	return fout;
}

void mx_to_c_PointerTons2__TagValueArray(const mxArray* a,ns2__TagValueArray **b)
{
	mx_to_c_ns2__TagValueArray(a,*b);

}

mxArray* c_to_mx_PointerTons2__TagValue(ns2__TagValue *a)
{
	mxArray  *fout;
	fout = c_to_mx_ns2__TagValue(*a);
	return fout;
}

void mx_to_c_PointerTons2__TagValue(const mxArray* a,ns2__TagValue **b)
{
	mx_to_c_ns2__TagValue(a,*b);

}

mxArray* c_to_mx__QName(char *a)
{
	mxArray  *fout;
	fout = c_to_mx_byte(*a);
	return fout;
}

void mx_to_c__QName(const mxArray* a,char **b)
{
	mx_to_c_byte(a,*b);

}

mxArray* c_to_mx_string(char *a)
{
	mxArray  *fout;
	fout = c_to_mx_byte(*a);
	return fout;
}

void mx_to_c_string(const mxArray* a,char **b)
{
	mx_to_c_byte(a,*b);

}
