/* soaprdLiteProxy.cpp
   Generated by gSOAP 2.8.14 from rdlite.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soaprdLiteProxy.h"

rdLiteProxy::rdLiteProxy()
{	rdLiteProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

rdLiteProxy::rdLiteProxy(const struct soap &_soap) : soap(_soap)
{ }

rdLiteProxy::rdLiteProxy(const char *url)
{	rdLiteProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

rdLiteProxy::rdLiteProxy(soap_mode iomode)
{	rdLiteProxy_init(iomode, iomode);
}

rdLiteProxy::rdLiteProxy(const char *url, soap_mode iomode)
{	rdLiteProxy_init(iomode, iomode);
	soap_endpoint = url;
}

rdLiteProxy::rdLiteProxy(soap_mode imode, soap_mode omode)
{	rdLiteProxy_init(imode, omode);
}

rdLiteProxy::~rdLiteProxy()
{ }

void rdLiteProxy::rdLiteProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "urn:rdLite", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
}

void rdLiteProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void rdLiteProxy::reset()
{	destroy();
	soap_done(this);
	soap_init(this);
	rdLiteProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void rdLiteProxy::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *rdLiteProxy::soap_header()
{	return this->header;
}

const SOAP_ENV__Fault *rdLiteProxy::soap_fault()
{	return this->fault;
}

const char *rdLiteProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *rdLiteProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int rdLiteProxy::soap_close_socket()
{	return soap_closesock(this);
}

int rdLiteProxy::soap_force_close_socket()
{	return soap_force_closesock(this);
}

void rdLiteProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void rdLiteProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *rdLiteProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int rdLiteProxy::Read(const char *endpoint, const char *soap_action, _ns1__Read *ns1__Read, _ns1__ReadResponse *ns1__ReadResponse)
{	struct soap *soap = this;
	struct __ns1__Read soap_tmp___ns1__Read;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.1.59:1662";
	if (soap_action == NULL)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__Read.ns1__Read = ns1__Read;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__Read(soap, &soap_tmp___ns1__Read);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__Read(soap, &soap_tmp___ns1__Read, "-ns1:Read", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__Read(soap, &soap_tmp___ns1__Read, "-ns1:Read", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__ReadResponse)
		return soap_closesock(soap);
	ns1__ReadResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__ReadResponse->soap_get(soap, "ns1:ReadResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int rdLiteProxy::Query(const char *endpoint, const char *soap_action, _ns1__Query *ns1__Query, _ns1__QueryResponse *ns1__QueryResponse)
{	struct soap *soap = this;
	struct __ns1__Query soap_tmp___ns1__Query;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.1.59:1662";
	if (soap_action == NULL)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__Query.ns1__Query = ns1__Query;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__Query(soap, &soap_tmp___ns1__Query);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__Query(soap, &soap_tmp___ns1__Query, "-ns1:Query", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__Query(soap, &soap_tmp___ns1__Query, "-ns1:Query", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__QueryResponse)
		return soap_closesock(soap);
	ns1__QueryResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__QueryResponse->soap_get(soap, "ns1:QueryResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
