/* soaprdLiteProxy.h
   Generated by gSOAP 2.8.14 from rdlite.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soaprdLiteProxy_H
#define soaprdLiteProxy_H
#include "soapH.h"

class SOAP_CMAC rdLiteProxy : public soap
{ public:
	/// Endpoint URL of service 'rdLiteProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	rdLiteProxy();
	/// Construct from another engine state
	rdLiteProxy(const struct soap&);
	/// Constructor with endpoint URL
	rdLiteProxy(const char *url);
	/// Constructor with engine input+output mode control
	rdLiteProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	rdLiteProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	rdLiteProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~rdLiteProxy();
	/// Initializer used by constructors
	virtual	void rdLiteProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'Read' (returns error code or SOAP_OK)
	virtual	int Read(_ns1__Read *ns1__Read, _ns1__ReadResponse *ns1__ReadResponse) { return this->Read(NULL, NULL, ns1__Read, ns1__ReadResponse); }
	virtual	int Read(const char *endpoint, const char *soap_action, _ns1__Read *ns1__Read, _ns1__ReadResponse *ns1__ReadResponse);

	/// Web service operation 'Query' (returns error code or SOAP_OK)
	virtual	int Query(_ns1__Query *ns1__Query, _ns1__QueryResponse *ns1__QueryResponse) { return this->Query(NULL, NULL, ns1__Query, ns1__QueryResponse); }
	virtual	int Query(const char *endpoint, const char *soap_action, _ns1__Query *ns1__Query, _ns1__QueryResponse *ns1__QueryResponse);
};
#endif
