/* soaprdliteProxy.h
   Generated by gSOAP 2.8.14 from rdlite.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soaprdliteProxy_H
#define soaprdliteProxy_H
#include "soapH.h"

class SOAP_CMAC rdliteProxy : public soap
{ public:
	/// Endpoint URL of service 'rdliteProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	rdliteProxy();
	/// Construct from another engine state
	rdliteProxy(const struct soap&);
	/// Constructor with endpoint URL
	rdliteProxy(const char *url);
	/// Constructor with engine input+output mode control
	rdliteProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	rdliteProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	rdliteProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~rdliteProxy();
	/// Initializer used by constructors
	virtual	void rdliteProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'CreateSubscription' (returns error code or SOAP_OK)
	virtual	int CreateSubscription(unsigned char stationId, int &result) { return this->CreateSubscription(NULL, NULL, stationId, result); }
	virtual	int CreateSubscription(const char *endpoint, const char *soap_action, unsigned char stationId, int &result);

	/// Web service operation 'AddSubscriptionItem' (returns error code or SOAP_OK)
	virtual	int AddSubscriptionItem(unsigned char stationId, int subId, ns2__TagIdArray *tagId, int &result) { return this->AddSubscriptionItem(NULL, NULL, stationId, subId, tagId, result); }
	virtual	int AddSubscriptionItem(const char *endpoint, const char *soap_action, unsigned char stationId, int subId, ns2__TagIdArray *tagId, int &result);

	/// Web service operation 'RefreshSubscription' (returns error code or SOAP_OK)
	virtual	int RefreshSubscription(unsigned char stationId, int subId, struct ns2__RefreshSubscriptionResponse &_param_1) { return this->RefreshSubscription(NULL, NULL, stationId, subId, _param_1); }
	virtual	int RefreshSubscription(const char *endpoint, const char *soap_action, unsigned char stationId, int subId, struct ns2__RefreshSubscriptionResponse &_param_1);

	/// Web service operation 'RemoveSubscription' (returns error code or SOAP_OK)
	virtual	int RemoveSubscription(unsigned char stationId, int subId, int &result) { return this->RemoveSubscription(NULL, NULL, stationId, subId, result); }
	virtual	int RemoveSubscription(const char *endpoint, const char *soap_action, unsigned char stationId, int subId, int &result);

	/// Web service operation 'Read' (returns error code or SOAP_OK)
	virtual	int Read(unsigned char stationId, ns2__TagIdArray *tagId, struct ns2__ReadResponse &_param_2) { return this->Read(NULL, NULL, stationId, tagId, _param_2); }
	virtual	int Read(const char *endpoint, const char *soap_action, unsigned char stationId, ns2__TagIdArray *tagId, struct ns2__ReadResponse &_param_2);

	/// Web service operation 'Query' (returns error code or SOAP_OK)
	virtual	int Query(unsigned char stationId, ns2__TagIdArray *tagId, unsigned char valueType, LONG64 beginTime, LONG64 endTime, unsigned short count, struct ns2__QueryResponse &_param_3) { return this->Query(NULL, NULL, stationId, tagId, valueType, beginTime, endTime, count, _param_3); }
	virtual	int Query(const char *endpoint, const char *soap_action, unsigned char stationId, ns2__TagIdArray *tagId, unsigned char valueType, LONG64 beginTime, LONG64 endTime, unsigned short count, struct ns2__QueryResponse &_param_3);

	/// Web service operation 'SetTag' (returns error code or SOAP_OK)
	virtual	int SetTag(unsigned char stationId, unsigned int id, unsigned short metaId, int &result) { return this->SetTag(NULL, NULL, stationId, id, metaId, result); }
	virtual	int SetTag(const char *endpoint, const char *soap_action, unsigned char stationId, unsigned int id, unsigned short metaId, int &result);

	/// Web service operation 'EnableTag' (returns error code or SOAP_OK)
	virtual	int EnableTag(unsigned char stationId, unsigned int id, bool enable, int &result) { return this->EnableTag(NULL, NULL, stationId, id, enable, result); }
	virtual	int EnableTag(const char *endpoint, const char *soap_action, unsigned char stationId, unsigned int id, bool enable, int &result);

	/// Web service operation 'SetMeta' (returns error code or SOAP_OK)
	virtual	int SetMeta(unsigned char stationId, unsigned short id, int index, std::string name, int dataLen, bool isValue, bool isAlarm, int &result) { return this->SetMeta(NULL, NULL, stationId, id, index, name, dataLen, isValue, isAlarm, result); }
	virtual	int SetMeta(const char *endpoint, const char *soap_action, unsigned char stationId, unsigned short id, int index, std::string name, int dataLen, bool isValue, bool isAlarm, int &result);

	/// Web service operation 'RemvoeMeta' (returns error code or SOAP_OK)
	virtual	int RemvoeMeta(unsigned char stationId, unsigned short id, int &result) { return this->RemvoeMeta(NULL, NULL, stationId, id, result); }
	virtual	int RemvoeMeta(const char *endpoint, const char *soap_action, unsigned char stationId, unsigned short id, int &result);

	/// Web service operation 'SetStation' (returns error code or SOAP_OK)
	virtual	int SetStation(unsigned char id, std::string name, bool isScada, std::string recvHost, unsigned short recvPort, std::string syncHost, unsigned short syncPort, int &result) { return this->SetStation(NULL, NULL, id, name, isScada, recvHost, recvPort, syncHost, syncPort, result); }
	virtual	int SetStation(const char *endpoint, const char *soap_action, unsigned char id, std::string name, bool isScada, std::string recvHost, unsigned short recvPort, std::string syncHost, unsigned short syncPort, int &result);

	/// Web service operation 'EnableStation' (returns error code or SOAP_OK)
	virtual	int EnableStation(unsigned char id, bool enabled, int &result) { return this->EnableStation(NULL, NULL, id, enabled, result); }
	virtual	int EnableStation(const char *endpoint, const char *soap_action, unsigned char id, bool enabled, int &result);

	/// Web service operation 'RemoveStation' (returns error code or SOAP_OK)
	virtual	int RemoveStation(unsigned char id, int &result) { return this->RemoveStation(NULL, NULL, id, result); }
	virtual	int RemoveStation(const char *endpoint, const char *soap_action, unsigned char id, int &result);
};
#endif
